[package]
name = "rustlex"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proc_macro_lib = { path = "proc_macro_lib" }
decl_macro_lib = { path = "decl_macro_lib" }
regex = "1.9.5"
